# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin_replay',
            field=models.BooleanField(default=False, verbose_name='Odpowied\u017a od administratora?'),
        ),
    ]
