# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna?')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer seryjny')),
            ],
            options={
                'verbose_name': 'Stacja',
                'verbose_name_plural': 'Stacje',
            },
        ),
    ]
