# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa taryfy')),
            ],
            options={
                'verbose_name': 'Taryfa',
                'verbose_name_plural': 'Taryfy',
            },
        ),
        migrations.RemoveField(
            model_name='meterpointstate',
            name='tariff_zone',
        ),
        migrations.RemoveField(
            model_name='tariffdefinition',
            name='tariff_zone',
        ),
        migrations.AddField(
            model_name='tariffdefinition',
            name='tariff_type',
            field=models.SmallIntegerField(choices=[(3, 'Strefa 3'), (2, 'Strefa 2'), (1, 'Strefa 1')], default=1, verbose_name='Strefa czasowa'),
        ),
        migrations.DeleteModel(
            name='TariffZone',
        ),
        migrations.AddField(
            model_name='meterpointstate',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Tariff', verbose_name='Taryfa'),
        ),
        migrations.AddField(
            model_name='tariffdefinition',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Tariff', verbose_name='Taryfa'),
        ),
    ]
