# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(verbose_name='Limit')),
                ('period', models.IntegerField(verbose_name='Okres')),
                ('period_type', models.SmallIntegerField(verbose_name='Typ okresu')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarmy',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa modelu')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Numer seryjny')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny?')),
                ('detection_report_date', models.DateTimeField(verbose_name='')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Station', verbose_name='Stacja')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='U\u017cytkownicy')),
            ],
            options={
                'verbose_name': 'Licznik',
                'verbose_name_plural': 'Liczniki',
            },
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acq_time', models.DateTimeField(verbose_name='')),
                ('cap_time', models.DateTimeField(verbose_name='')),
                ('flags', models.CharField(max_length=32, verbose_name='Flagi')),
                ('reason', models.SmallIntegerField(verbose_name='')),
                ('scaler_scaler', models.IntegerField(verbose_name='')),
                ('scaler_unit', models.IntegerField(verbose_name='')),
                ('value', models.BigIntegerField(verbose_name='Warto\u015b\u0107 pomiaru')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Meter', verbose_name='Licznik')),
            ],
            options={
                'verbose_name': 'Pomiar',
                'verbose_name_plural': 'Pomiary',
            },
        ),
        migrations.CreateModel(
            name='MeterObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='')),
                ('description', models.CharField(max_length=500, verbose_name='')),
                ('frequency', models.SmallIntegerField(verbose_name='')),
                ('incremental_chart', models.BooleanField(verbose_name='')),
                ('obis', models.CharField(max_length=32, verbose_name='')),
                ('precision', models.SmallIntegerField(verbose_name='')),
                ('unit', models.SmallIntegerField(verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Opis')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Adres')),
                ('ppe_code', models.CharField(max_length=255, verbose_name='Kod PPE')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny?')),
                ('flags', models.CharField(blank=True, max_length=32, null=True, verbose_name='Flagi')),
                ('status_change_date', models.DateTimeField(verbose_name='')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Station', verbose_name='Stacja')),
            ],
            options={
                'verbose_name': 'Punkt pomiaru',
                'verbose_name_plural': 'Punkty pomiaru',
            },
        ),
        migrations.CreateModel(
            name='MeterPointState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Rozpocz\u0105\u0142 dzia\u0142anie')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Zako\u0144czy\u0142 dzia\u0142anie')),
                ('current_power_limit', models.IntegerField(verbose_name='Limit mocy')),
                ('start_value', models.IntegerField(default=0, verbose_name='Warto\u015b\u0107 pocz\u0105tkowa')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Meter', verbose_name='Licznik')),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.MeterPoint', verbose_name='Punkt pomiaru')),
            ],
            options={
                'verbose_name': 'Stan punktu pomiaru',
                'verbose_name_plural': 'Stany punkt\xf3w pomiar\xf3w',
            },
        ),
        migrations.CreateModel(
            name='TariffDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Godzina startu')),
                ('end_hour', models.TimeField(verbose_name='Godzina ko\u0144ca')),
            ],
            options={
                'verbose_name': 'Definicja strefy czasowej',
                'verbose_name_plural': 'Definicje stref czasowych',
            },
        ),
        migrations.CreateModel(
            name='TariffZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa strefy')),
                ('obis', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Strefa czasowa',
                'verbose_name_plural': 'Strefy czasowe',
            },
        ),
        migrations.AddField(
            model_name='tariffdefinition',
            name='tariff_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.TariffZone', verbose_name='Strefa czasowa'),
        ),
        migrations.AddField(
            model_name='meterpointstate',
            name='tariff_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.TariffZone', verbose_name='Strefa czasowa'),
        ),
        migrations.AddField(
            model_name='meterdata',
            name='meter_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.MeterObject', verbose_name='Obiekt pomiaru'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Meter', verbose_name='Licznik'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='U\u017cytkownik'),
        ),
    ]
