# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20161121_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterobject',
            options={'verbose_name': 'Obiekt pomiaru', 'verbose_name_plural': 'Obiekty pomiar\xf3w'},
        ),
        migrations.AlterField(
            model_name='alarm',
            name='period_type',
            field=models.SmallIntegerField(choices=[(1, b'Godzin (-y)'), (3, b'Tygodnia (-dni)'), (4, b'Mieci\xc4\x85ca (-cy)'), (2, b'Doby / D\xc3\xb3b')], verbose_name='Typ okresu'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='detection_report_date',
            field=models.DateTimeField(verbose_name='Data wykrycia licznika przez AMI'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='acq_time',
            field=models.DateTimeField(verbose_name='Data pomiaru'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='cap_time',
            field=models.IntegerField(default=15, verbose_name='Cz\u0119stotliwo\u015b\u0107 pomiaru (minuty)'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='reason',
            field=models.SmallIntegerField(choices=[(0, 'Pomiar Automatyczny'), (1, 'Warto\u015b\u0107 wprowadzona r\u0119cznie')], default=0, verbose_name='Typ pomiaru'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='scaler_scaler',
            field=models.IntegerField(verbose_name='Warto\u015b\u0107 normalizacji'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='scaler_unit',
            field=models.SmallIntegerField(choices=[(0, 'KWh'), (1, 'MWH')], default=0, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='alias',
            field=models.CharField(max_length=255, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='frequency',
            field=models.SmallIntegerField(verbose_name='Cz\u0119stotliwo\u015b\u0107'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='incremental_chart',
            field=models.BooleanField(default=True, verbose_name='Czy warto\u015b\u0107 w stosunku do poprzednego pomiaru wzros\u0142a?'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='obis',
            field=models.CharField(max_length=32, verbose_name='OBIS'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='precision',
            field=models.SmallIntegerField(verbose_name='Precyzja'),
        ),
        migrations.AlterField(
            model_name='meterobject',
            name='unit',
            field=models.SmallIntegerField(verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='status_change_date',
            field=models.DateTimeField(verbose_name='Data ostatniej zmiany statusu'),
        ),
    ]
