# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0004_auto_20161203_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMainMeterPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.MeterPoint', verbose_name='Punkt pomiaru')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='U\u017cytkownik')),
            ],
            options={
                'verbose_name': 'Licznik g\u0142\xf3wny',
                'verbose_name_plural': 'Liczniki g\u0142\xf3wne',
            },
        ),
    ]
