# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_usermainmeterpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermainmeterpoint',
            name='meter_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.MeterPoint', verbose_name='Punkt pomiaru'),
        ),
    ]
