# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_notice_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdown',
            options={'verbose_name': 'Wy\u0142\u0105czenie', 'verbose_name_plural': 'Wy\u0142\u0105czenia'},
        ),
        migrations.AddField(
            model_name='breakdown',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Pow\xf3d'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='end_at',
            field=models.DateTimeField(verbose_name='Data zako\u0144czenia'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='start_at',
            field=models.DateTimeField(verbose_name='Data rozpocz\u0119cia'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='stations',
            field=models.ManyToManyField(to='structure.Station', verbose_name='Stacje obj\u0119te wy\u0142\u0105czeniem'),
        ),
    ]
